"""del msg

Revision ID: c561d406599c
Revises: e1e9b9c192bc
Create Date: 2021-01-30 09:53:49.238785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c561d406599c'
down_revision = 'e1e9b9c192bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msg', sa.Column('is_delete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('msg', 'is_delete')
    # ### end Alembic commands ###
